---
- name: Install Wordpress on EC2
  hosts: aws_ec2
  become: yes
  become_method: sudo
  connection: ssh
  roles:
  - wordpress
  - users
  - upgrade 
 
#ansible-playbook playbook.yaml

        

  
 
