- name: First Playbook
  hosts: aws_ec2
  become: yes
  become_method: sudo
  connection: ssh
  tasks:
  - name: Display nodename
    ansible.builtin.debug:
      var: ansible_facts['nodename'] # specify inside [] to get speficic facts about the localhost. If don`t specify it will bring all facts.
 
  - name: Display kernel info
    ansible.builtin.debug:
      var: ansible_facts['kernel'] 

  - name: Display os_family
    ansible.builtin.debug:
      var: ansible_facts['os_family']

  - name: Display Distribution
    ansible.builtin.debug:
      var: ansible_facts['distribution']

  - name: Display Distribution major version
    ansible.builtin.debug:
      var: ansible_facts['distribution_major_version']

  - name: Display Ipv4 addresses
    ansible.builtin.debug:
      var: ansible_facts['all_ipv4_addresses']