- name: First Playbook
  hosts: aws_ec2      #to install to specific hosts =====>   #tag_Name_ansible_ubuntu     #tag_Name_ansible_amazon
  become: yes
  become_method: sudo
  connection: ssh
  tasks:
  - name: install the latest version of Apache
    yum:
      name: telnet
      state: present #latest or absent