---
- name: lineinfile
  hosts: amazon 
  become: true
  become_method: sudo
  connection: ssh
  tasks:
  - name: Download wordpress
    ansible.builtin.get_url:
      url: https://wordpress.org/latest.tar.gz
      dest: /tmp/wordpress.tar.gz

  - name: Extract wordpress
    ansible.builtin.unarchive:
      src: /tmp/wordpress.tar.gz
      dest: /tmp/
      remote_src: yes
        

# to execute: ansible-playbook -i ../inventory download.yaml