--- # Connection block
- name: First Playbook
  hosts: localhost
  become: yes
  become_method: sudo
  connection: ssh
  tasks:
  - name: install the latest version of Apache
    yum:
      name: httpd
      state: latest #latest or absent

  - name: install the latest version of Telnet
    yum:
      name: telnet
      state: latest    

  - name: install the latest version of elinks
    yum:
      name: elinks
      state: latest

  - name: install the latest version of lftp
    yum:
      name: lftp
      state: latest
      
  - name: install the latest version of php
    yum:
      name: php
      state: latest



# to execute : ansible-playbook playbook.yaml