---
- name: lineinfile
  hosts: amazon 
  become: true
  become_method: sudo
  connection: ssh
  tasks:
  - name: Add a line to a file if the file does not exist, without passing regexp
    ansible.builtin.lineinfile:
      path: /tmp/testfile
      line: 192.168.1.99 foo.lab.net foo
      create: yes

  - name: Ensure testfile content is changed.
    ansible.builtin.lineinfile:
      path: /tmp/testfile
      regexp: '^192.168.1.99' #using carrot(^) find line starts with 192.168.1.99
      line: '172.16.1.99 foo.lab.net foo' # changes to line to 172.16.1.99 foo.lab.net foo as specified.


# to execute: ansible-playbook -i ../inventory lineinfile.yaml