---
- name: Playbook class2
  hosts: all
  become: true
  become_method: sudo
  connection: ssh
  tasks:
  - name: install telnet
    ansible.builtin.package: # package means it will run appropriate command depending on the Operating system ex: yum or apt
     name: telnet
     state: latest # state can be modified as absent or present


# to execute: ansible-playbook -i ../inventory playbook2.yaml