---
- name: Playbook class2
  hosts: amazon #hosts can be specified depending on the inventory file IP and groups or even DNS names.
  become: true
  become_method: sudo
  connection: ssh
  tasks:
  - name: install telnet
    ansible.builtin.package: # package means it will run appropriate command depending on the Operating system ex: yum or apt
     name: telnet
     state: latest # state can be modified as absent or present

  - name: Add the user 'johnd'
    ansible.builtin.user:
      name: johnd

  - name: Ensure group "sales" exists
    ansible.builtin.group:
      name: sales
      state: present


# to execute: ansible-playbook -i ../inventory playbook2.yaml

# to check for any errors run : ansible-lint playbook2.yaml