---
- name: Playbook to update packages
  hosts: all
  become: true
  become_method: sudo
  connection: ssh
  tasks:
  - name: update
    ansible.builtin.package: 
     name: kernel
     state: latest 
    ignore_errors: true 

  - name: update
    ansible.builtin.package: 
     name: "*" # updates entire linux system
     state: latest 
    ignore_errors: true 


# to execute: ansible-playbook -i ../inventory update.yaml