---
- name: Playbook to add multiple packages
  hosts: all 
  become: true
  become_method: sudo
  connection: ssh
  tasks:
  - name: Add multiple packages
    package:
      name: "{{ item }}"
      state: latest
    with_items:
    - telnet
    - httpd
    - php
    - lftp

    # to execute: ansible-playbook  add_multiple_packages.yaml